package com.emse.spring.faircorp.hello;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.system.CapturedOutput;
import org.springframework.boot.test.system.OutputCaptureExtension;

/**
 *  test class for display services when the application is opened (= Greeting services)
 */
// We load a Junit5 extension to capture the output (log generated by our application)
@ExtendWith(OutputCaptureExtension.class)
class GreetingServiceTest {

     /**
     * unit test to verify that the ConsoleGreetingService returns the string "Hello, Spring!"
     * when passing the string "Spring" to its greet method
     * @param output    what is displayed in the console
     */
    @Test
    public void testGreeting(CapturedOutput output) {
        // We’re testing our service implementation without Spring being involved.
        // So we create a new instance of this service with a new
        GreetingService greetingService = new ConsoleGreetingService();
        greetingService.greet("Spring");
        Assertions.assertThat(output.getAll()).contains("Hello, Spring!");
    }
}
